"""
Random-mask inpainting training using deepinv physics.

Forward model:  deepinv.physics.Inpainting with per-batch Bernoulli masks
                generated by BernoulliSplittingMaskGenerator.
Network input:  cat([y_or_proxy, mask_1c], dim=1)  — C+1 channels.
TV proxy:       optional Chambolle PGD on GPU; see --use_proxy.
"""

import os
import glob
import random
import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tensorboardX import SummaryWriter

import deepinv
from deepinv.physics import Inpainting
from deepinv.physics.generator import BernoulliSplittingMaskGenerator

try:
    import wandb
    WANDB_AVAILABLE = True
except ImportError:
    WANDB_AVAILABLE = False

from utils.models import UNetDeblur, UNetRes
from utils.utils import batch_psnr, init_logger


# ── TV proxy (Chambolle PGD, pure PyTorch, GPU-friendly) ──────────────────────

def _grad_op(x: torch.Tensor) -> torch.Tensor:
    """Forward finite differences: (B,C,H,W) → (B,C,2,H,W)."""
    B, C, H, W = x.shape
    g = torch.zeros(B, C, 2, H, W, device=x.device, dtype=x.dtype)
    g[:, :, 0, :-1, :] = x[:, :, 1:,  :] - x[:, :, :-1, :]   # h-direction
    g[:, :, 1, :, :-1] = x[:, :, :,  1:] - x[:, :, :, :-1]   # w-direction
    return g


def _div_op(p: torch.Tensor) -> torch.Tensor:
    """Backward divergence (adjoint of _grad_op): (B,C,2,H,W) → (B,C,H,W)."""
    B, C, _, H, W = p.shape
    d = torch.zeros(B, C, H, W, device=p.device, dtype=p.dtype)
    d[:, :, 1:,  :] += p[:, :, 0, :-1, :]
    d[:, :, :-1, :] -= p[:, :, 0, :-1, :]
    d[:, :, :, 1:]  += p[:, :, 1, :, :-1]
    d[:, :, :, :-1] -= p[:, :, 1, :, :-1]
    return d


@torch.no_grad()
def _chambolle_tv_denoise(f: torch.Tensor, lam: float, n_iter: int = 15) -> torch.Tensor:
    """
    Chambolle (2004) dual-ascent TV denoising.
    Solves: argmin_x (1/2)||x - f||^2 + lam * TV(x).

    All ops are batched and run on whatever device f lives on.
    τ = 1/8 guarantees convergence for anisotropic TV with 4-connectivity.
    """
    p = torch.zeros(*f.shape[:2], 2, *f.shape[2:], device=f.device, dtype=f.dtype)
    tau = 0.125  # ≤ 1/8

    for _ in range(n_iter):
        r = _div_op(p) - f / lam
        g = _grad_op(r)
        p_new = p + tau * g
        norm = (p_new ** 2).sum(dim=2, keepdim=True).sqrt_().clamp_(min=1.0)
        p = p_new / norm

    return f - lam * _div_op(p)


@torch.no_grad()
def tv_inpaint_proxy(
    y: torch.Tensor,
    mask_1c: torch.Tensor,
    n_pgd: int = 5,
    lam: float = 0.05,
    tv_iters: int = 15,
) -> torch.Tensor:
    """
    PGD with TV proximity for inpainting (Chambolle inner solver).

    Solves: argmin_x  (1/2)||mask*(x - y)||^2 + lam * TV(x)

    Each outer PGD step:
      1. Gradient step (α=1/L=1): z = mask*y + (1-mask)*x
         (enforces observed pixels, leaves missing pixels from current estimate)
      2. TV prox step: x ← argmin_u (1/2)||u-z||^2 + lam*TV(u)

    Args:
        y       : (B, C, H, W) zero-filled measurement (physics.A_adjoint output).
        mask_1c : (B, 1, H, W) binary mask, 1 = observed pixel.
        n_pgd   : number of outer PGD iterations (default 5).
        lam     : TV regularisation weight (default 0.05).
        tv_iters: Chambolle inner iterations per PGD step (default 15).
    """
    x = y.clone()
    for _ in range(n_pgd):
        z = mask_1c * y + (1.0 - mask_1c) * x   # gradient step
        x = _chambolle_tv_denoise(z, lam, n_iter=tv_iters)
    return x.clamp_(0.0, 1.0)


# ── Dataset (clean patches only; corruption applied on GPU in training loop) ──

class PatchDataset(Dataset):
    """On-the-fly clean-patch dataset.

    Mask generation and physics forward are handled in the training loop on GPU
    to benefit from batch-level parallelism.
    """

    def __init__(self, image_dir: str, patch_size: int = 128, gray: bool = False,
                 virtual_length: int = 200_000):
        exts = ('*.png', '*.jpg', '*.jpeg', '*.bmp', '*.tif', '*.tiff')
        self.image_paths: list[str] = []
        for ext in exts:
            self.image_paths.extend(glob.glob(os.path.join(image_dir, ext)))
        if not self.image_paths:
            raise ValueError(f"No images found in {image_dir}")
        self.image_paths.sort()

        self.patch_size    = patch_size
        self.gray          = gray
        self.virtual_length = virtual_length

    def __len__(self) -> int:
        return self.virtual_length

    def __getitem__(self, idx: int) -> torch.Tensor:
        path = self.image_paths[idx % len(self.image_paths)]
        img  = cv2.imread(path)
        if img is None:
            img = cv2.imread(random.choice(self.image_paths))

        if self.gray:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)[:, :, np.newaxis]
        else:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = img.astype(np.float32) / 255.0   # H × W × C

        p = self.patch_size
        h, w = img.shape[:2]
        if h < p or w < p:
            img = cv2.resize(img, (max(w, p + 4), max(h, p + 4)),
                             interpolation=cv2.INTER_CUBIC)
            if img.ndim == 2:
                img = img[:, :, np.newaxis]
            h, w = img.shape[:2]

        top  = np.random.randint(0, h - p + 1)
        left = np.random.randint(0, w - p + 1)
        patch = img[top:top + p, left:left + p].copy()

        # 8-fold symmetry augmentation
        k = np.random.randint(0, 8)
        patch = np.rot90(patch, k=k % 4)
        if k >= 4:
            patch = np.fliplr(patch)

        return torch.from_numpy(np.ascontiguousarray(patch.transpose(2, 0, 1)))


# ── Training ──────────────────────────────────────────────────────────────────

def train_inpaint(args):
    torch.manual_seed(42)
    np.random.seed(42)

    in_ch    = 1 if args.gray else 3
    net_in_ch = in_ch + 1     # image channels + 1-channel binary mask

    dataset_train = PatchDataset(
        args.train_dir, patch_size=args.patch_size, gray=args.gray,
        virtual_length=max(500_000, args.max_steps * args.batch_size),
    )
    dataset_val = PatchDataset(
        args.val_dir, patch_size=256, gray=args.gray, virtual_length=50,
    )
    print(f"  Train images  : {len(dataset_train.image_paths)}")
    print(f"  Val   images  : {len(dataset_val.image_paths)}")
    print(f"  Network in_ch : {net_in_ch}  (image={in_ch} + mask=1)")
    print(f"  p_keep range  : [{args.p_keep_min}, {args.p_keep_max}]")
    proxy_desc = (
        f"TV Chambolle ({args.proxy_pgd_iters} PGD × {args.proxy_tv_iters} TV iters, "
        f"λ={args.proxy_lam})"
        if args.use_proxy else "none (zero-fill)"
    )
    print(f"  Proxy init    : {proxy_desc}")

    # ── deepinv physics objects ──────────────────────────────────────────────
    # One generator per split (different spatial sizes); spatial size overridden
    # per step via gen.step(img_size=(H, W)).
    mask_gen_train = BernoulliSplittingMaskGenerator(
        img_size=(1, args.patch_size, args.patch_size),
        split_ratio=(args.p_keep_min + args.p_keep_max) / 2.0,
        pixelwise=True,
        random_split_ratio=True,
        min_split_ratio=args.p_keep_min,
        max_split_ratio=args.p_keep_max,
        device='cuda',
    )
    mask_gen_val = BernoulliSplittingMaskGenerator(
        img_size=(1, 256, 256),
        split_ratio=(args.p_keep_min + args.p_keep_max) / 2.0,
        pixelwise=True,
        random_split_ratio=True,
        min_split_ratio=args.p_keep_min,
        max_split_ratio=args.p_keep_max,
        device='cuda',
    )

    # Physics operator — mask is updated per batch via update_parameters()
    physics = Inpainting(
        img_size=(in_ch, args.patch_size, args.patch_size),
        mask=args.p_keep_min,      # placeholder; overwritten each step
        pixelwise=True,
        device='cuda',
    )

    # ── Loggers ──────────────────────────────────────────────────────────────
    log_path = os.path.join("TRAINING_LOGS", args.log_dir)
    os.makedirs(log_path, exist_ok=True)
    writer = SummaryWriter(log_path)
    logger = init_logger(args)

    use_wandb = args.wandb and WANDB_AVAILABLE
    if args.wandb and not WANDB_AVAILABLE:
        print("Warning: wandb not installed — skipping wandb logging.")
    if use_wandb:
        wandb.init(
            project=args.wandb_project,
            name=args.wandb_run or args.log_dir,
            config=vars(args),
            mode="offline",
        )

    # ── Model ─────────────────────────────────────────────────────────────────
    if args.model == 'UNetDeblur':
        net = UNetDeblur(in_nc=net_in_ch, out_nc=in_ch, nc=(64, 128, 256, 512))
    elif args.model == 'UNetRes':
        net = UNetRes(in_nc=net_in_ch, out_nc=in_ch, nc=[64, 128, 256, 512], nb=4)
    else:
        raise ValueError(f"Unknown model: {args.model}")

    model     = net.cuda()
    criterion = nn.L1Loss(reduction='sum').cuda()
    optimizer = optim.Adam(model.parameters(), lr=args.lr)

    loader_train = DataLoader(
        dataset_train, batch_size=args.batch_size,
        shuffle=True, num_workers=args.num_workers,
        pin_memory=True, drop_last=True,
    )
    loader_val = DataLoader(
        dataset_val, batch_size=1, shuffle=False, num_workers=2,
    )

    step       = 0
    current_lr = args.lr

    if args.resume_training:
        ckpt_file = os.path.join(log_path, args.check_point)
        if os.path.isfile(ckpt_file):
            ckpt = torch.load(ckpt_file)
            model.load_state_dict(ckpt['state_dict'])
            optimizer.load_state_dict(ckpt['optimizer'])
            step       = ckpt['step']
            current_lr = ckpt['current_lr']
            for pg in optimizer.param_groups:
                pg['lr'] = current_lr
            print(f"> Resumed from step {step}, lr={current_lr:.2e}")
        else:
            raise FileNotFoundError(f"Checkpoint not found: {ckpt_file}")

    print(f"\n> Training starts at step {step} / {args.max_steps}")
    data_iter = iter(loader_train)

    while step < args.max_steps:

        # ── LR decay ──────────────────────────────────────────────────────────
        if step > 0 and step % args.steps_per_lr == 0:
            new_lr = max(current_lr * 0.5, args.min_lr)
            if new_lr != current_lr:
                current_lr = new_lr
                for pg in optimizer.param_groups:
                    pg['lr'] = current_lr
                print(f"  [step {step:7d}] LR decayed -> {current_lr:.2e}")

        # ── Fetch clean batch ─────────────────────────────────────────────────
        try:
            clean = next(data_iter)
        except StopIteration:
            data_iter = iter(loader_train)
            clean = next(data_iter)
        clean = clean.cuda()                        # B × C × H × W
        B, C, H, W = clean.shape

        # ── Bernoulli mask (deepinv generator) ────────────────────────────────
        mask_1c = mask_gen_train.step(
            batch_size=B, img_size=(H, W)
        )['mask']                                   # B × 1 × H × W

        # ── Inpainting physics forward ────────────────────────────────────────
        physics.update_parameters(mask=mask_1c)     # broadcast to B × C × H × W
        y = physics(clean)                          # B × C × H × W, missing = 0

        # ── Optional TV proxy ─────────────────────────────────────────────────
        if args.use_proxy:
            proxy = tv_inpaint_proxy(
                y, mask_1c,
                n_pgd=args.proxy_pgd_iters,
                lam=args.proxy_lam,
                tv_iters=args.proxy_tv_iters,
            )
        else:
            proxy = y   # plain zero-fill

        # Network input: concat image estimate + mask channel
        inp = torch.cat([proxy, mask_1c], dim=1)    # B × (C+1) × H × W

        # ── Forward / backward ────────────────────────────────────────────────
        model.train()
        optimizer.zero_grad()
        out  = model(inp)
        loss = criterion(out, clean) / (B * 2)
        loss.backward()
        if args.grad_clip:
            nn.utils.clip_grad_norm_(model.parameters(), 0.5)
        optimizer.step()

        # ── Logging ───────────────────────────────────────────────────────────
        if step % args.log_every == 0:
            model.eval()
            with torch.no_grad():
                psnr = batch_psnr(torch.clamp(out.detach(), 0., 1.), clean, 1.)
            writer.add_scalar('loss',       loss.item(), step)
            writer.add_scalar('PSNR_train', psnr,        step)
            writer.add_scalar('lr',         current_lr,  step)
            if use_wandb:
                wandb.log({'loss': loss.item(), 'PSNR_train': psnr,
                           'lr': current_lr}, step=step)
            print(f"[step {step:7d}] loss={loss.item():.5f}  "
                  f"PSNR={psnr:.2f} dB  lr={current_lr:.2e}")

        # ── Validation ────────────────────────────────────────────────────────
        if step % args.val_every == 0 and step > 0:
            model.eval()
            psnr_val = 0.0
            with torch.no_grad():
                for clean_v in loader_val:
                    clean_v = clean_v.cuda()
                    Bv, Cv, Hv, Wv = clean_v.shape

                    mask_v = mask_gen_val.step(
                        batch_size=Bv, img_size=(Hv, Wv)
                    )['mask']
                    physics.update_parameters(mask=mask_v)
                    y_v = physics(clean_v)

                    if args.use_proxy:
                        proxy_v = tv_inpaint_proxy(
                            y_v, mask_v,
                            n_pgd=args.proxy_pgd_iters,
                            lam=args.proxy_lam,
                            tv_iters=args.proxy_tv_iters,
                        )
                    else:
                        proxy_v = y_v

                    inp_v = torch.cat([proxy_v, mask_v], dim=1)
                    out_v = torch.clamp(model(inp_v), 0., 1.)
                    psnr_val += batch_psnr(out_v, clean_v, 1.)

            psnr_val /= len(loader_val)
            writer.add_scalar('PSNR_val', psnr_val, step)
            if use_wandb:
                wandb.log({'PSNR_val': psnr_val}, step=step)
            print(f"  [val  {step:7d}] PSNR_val={psnr_val:.2f} dB")

        # ── Checkpoint ────────────────────────────────────────────────────────
        if step % args.save_every == 0 and step > 0:
            _save_checkpoint(model, optimizer, step, current_lr, args, log_path,
                             periodic=(step % (args.save_every * 10) == 0))
        step += 1

    _save_checkpoint(model, optimizer, step, current_lr, args, log_path,
                     periodic=True, tag='final')
    writer.close()
    if use_wandb:
        wandb.finish()
    print(f"\n> Done. Model saved to {log_path}/net.pth")


def _save_checkpoint(model, optimizer, step, current_lr, args, log_path,
                     periodic=False, tag=None):
    torch.save(model.state_dict(), os.path.join(log_path, 'net.pth'))
    ckpt = {
        'state_dict': model.state_dict(),
        'optimizer':  optimizer.state_dict(),
        'step':       step,
        'current_lr': current_lr,
        'args':       args,
    }
    torch.save(ckpt, os.path.join(log_path, 'ckpt.pth'))
    if tag:
        torch.save(ckpt, os.path.join(log_path, f'ckpt_{tag}.pth'))
    elif periodic:
        torch.save(ckpt, os.path.join(log_path, f'ckpt_step{step}.pth'))
